[package]
# This one licenses with %{crate_instdir}, but these are not installed there
# Manually remove that
license-files.include = [
    ".licenses/*"
]
cargo-install-bin = false

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Remove circular dependency with saphyr.",
    "# The circular dependency was stripped somehow.",
    "# tomcli set Cargo.toml del dev-dependencies.saphyr",
    "# Saphyr was used in the test-suite tests.",
    "tomcli set Cargo.toml lists delitem --key=path test 'tests/yaml-test-suite.rs'",
    "# Can also drop libtest-mimic because it is only used in yaml-test-suite.rs",
    "tomcli set Cargo.toml del dev-dependencies.libtest-mimic",
]
