[tests]
run = ["none"]
comments = ["outdated dev-dependencies: notify"]

[package]
cargo-toml-patch-comments = [
    """
    Relax ron dependency. Proper update is still worked on.
    https://github.com/rust-cli/config-rs/pull/476
    """,
]
