[features]
enable-all = true

[package]
cargo-toml-patch-comments = [
    "Remove dev-dependency on sqlx. It is used only for doctests.",
]

[tests]
skip = [
    "options::MySqlConnectOptions",
]
comments = [
    "Skip tests that require main sqlx package"
]

