[package]
cargo-toml-patch-comments = [
    """
    Remove dependency on coverage-helper
    https://github.com/sgodwincs/ordered-multimap-rs/pull/35
    """,
]

[scripts]
prep.post = [
    "# Remove dependency on coverage-helper.",
    "sed -i '/use coverage_helper::test/d' src/*.rs",
]
