_:
  - &actions-use-spec
    fix-spec-file: [ ]
    create-archive:
      - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
    get-current-version:
      - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  - &actions-rust2rpm
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm @${PACKIT_PROJECT_VERSION}'
  - &actions-rust2rpm-with-patch
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm -r @${PACKIT_PROJECT_VERSION}'

packages:
  # Main packages
  rust-sqlx:
    paths: [ rust-sqlx ]
    specfile_path: rust-sqlx.spec
    downstream_package_name: rust-sqlx
    actions: *actions-rust2rpm
  rust-sqlx-core:
    paths: [ rust-sqlx-core ]
    specfile_path: rust-sqlx-core.spec
    downstream_package_name: rust-sqlx-core
    actions: *actions-rust2rpm
  rust-sqlx-macros:
    paths: [ rust-sqlx-macros ]
    specfile_path: rust-sqlx-macros.spec
    downstream_package_name: rust-sqlx-macros
    actions: *actions-rust2rpm
  rust-sqlx-macros-core:
    paths: [ rust-sqlx-macros-core ]
    specfile_path: rust-sqlx-macros-core.spec
    downstream_package_name: rust-sqlx-macros-core
    actions: *actions-rust2rpm
  rust-sqlx-mysql:
    paths: [ rust-sqlx-mysql ]
    specfile_path: rust-sqlx-mysql.spec
    downstream_package_name: rust-sqlx-mysql
    actions: *actions-rust2rpm
  rust-sqlx-postgres:
    paths: [ rust-sqlx-postgres ]
    specfile_path: rust-sqlx-postgres.spec
    downstream_package_name: rust-sqlx-postgres
    actions: *actions-rust2rpm
  rust-sqlx-sqlite:
    paths: [ rust-sqlx-sqlite ]
    specfile_path: rust-sqlx-sqlite.spec
    downstream_package_name: rust-sqlx-sqlite
    actions: *actions-rust2rpm
  # Dependencies
  atuin:
    paths: [ atuin ]
    specfile_path: atuin.spec
    downstream_package_name: atuin
    actions: *actions-use-spec
  rust-backon:
    paths: [ rust-backon ]
    specfile_path: rust-backon.spec
    downstream_package_name: rust-backon
    actions: *actions-use-spec

srpm_build_deps:
  - rust2rpm
  - rust2rpm-helper

targets:
  - fedora-rawhide

jobs:
  - job: copr_build
    trigger: commit
    branch: impact-check/sqlx
    owner: lecris
    project: rust-sqlx
