_:
  - &actions-use-spec
    fix-spec-file: []
    create-archive:
      - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
    get-current-version:
      - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  - &actions-rust2rpm
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm @${PACKIT_PROJECT_VERSION}'
  - &actions-rust2rpm-with-patch
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm -r @${PACKIT_PROJECT_VERSION}'

packages:
  atuin:
    paths: [ atuin ]
    specfile_path: atuin.spec
    downstream_package_name: atuin
    upstream_package_name: atuin
    actions: *actions-use-spec
  rust-arraydeque:
    # For saphyr-parser
    paths: [ rust-arraydeque ]
    specfile_path: rust-arraydeque.spec
    downstream_package_name: rust-arraydeque
    upstream_package_name: axum-arraydeque
    actions: *actions-rust2rpm
  rust-axum-server:
    # For atuin
    paths: [ rust-axum-server ]
    specfile_path: rust-axum-server.spec
    downstream_package_name: rust-axum-server
    upstream_package_name: axum-server
    actions: *actions-rust2rpm
  rust-condtype:
    # For divan
    paths: [ rust-condtype ]
    specfile_path: rust-condtype.spec
    downstream_package_name: rust-condtype
    upstream_package_name: condtype
    actions: *actions-rust2rpm
  rust-config:
    # For atuin
    # https://bugzilla.redhat.com/show_bug.cgi?id=2262210
    paths: [ rust-config ]
    specfile_path: rust-config.spec
    downstream_package_name: rust-config
    upstream_package_name: config
    actions: *actions-rust2rpm
  rust-divan:
    # For atuin
    paths: [ rust-divan ]
    specfile_path: rust-divan.spec
    downstream_package_name: rust-divan
    upstream_package_name: divan
    actions: *actions-rust2rpm
  rust-divan-macros:
    # For divan
    paths: [ rust-divan-macros ]
    specfile_path: rust-divan-macros.spec
    downstream_package_name: rust-divan-macros
    upstream_package_name: divan-macros
    actions: *actions-rust2rpm
  rust-dlv-list:
    # For ordered-multimap
    # https://bugzilla.redhat.com/show_bug.cgi?id=1989392
    paths: [ rust-dlv-list ]
    specfile_path: rust-dlv-list.spec
    downstream_package_name: rust-dlv-list
    upstream_package_name: dlv-list
    actions: *actions-rust2rpm
  rust-font8x8:
    # For ratatui
    paths: [ rust-font8x8 ]
    specfile_path: rust-font8x8.spec
    downstream_package_name: rust-font8x8
    upstream_package_name: font8x8
    actions: *actions-rust2rpm
  rust-httptest:
    # For postmark
    paths: [ rust-httptest ]
    specfile_path: rust-httptest.spec
    downstream_package_name: rust-httptest
    upstream_package_name: httptest
    actions: *actions-rust2rpm
  rust-ordered-multimap:
    # For rust-ini
    # https://bugzilla.redhat.com/show_bug.cgi?id=1976416
    paths: [ rust-ordered-multimap ]
    specfile_path: rust-ordered-multimap.spec
    downstream_package_name: rust-ordered-multimap
    upstream_package_name: ordered-multimap
    actions: *actions-rust2rpm
  rust-postmark:
    # For atuin
    paths: [ rust-postmark ]
    specfile_path: rust-postmark.spec
    downstream_package_name: rust-postmark
    upstream_package_name: postmark
    actions: *actions-rust2rpm
  rust-prost-reflect:
    # For protox
    paths: [ rust-prost-reflect ]
    specfile_path: rust-prost-reflect.spec
    downstream_package_name: rust-prost-reflect
    upstream_package_name: prost-reflect
    actions: *actions-rust2rpm
  rust-protox:
    # For atuin
    paths: [ rust-protox ]
    specfile_path: rust-protox.spec
    downstream_package_name: rust-protox
    upstream_package_name: protox
    actions: *actions-rust2rpm
  rust-protox-parse:
    # For protox
    paths: [ rust-protox-parse ]
    specfile_path: rust-protox-parse.spec
    downstream_package_name: rust-protox-parse
    upstream_package_name: protox-parse
    actions: *actions-rust2rpm
  rust-ratatui:
    # For atuin
    # https://bugzilla.redhat.com/show_bug.cgi?id=2320186
    paths: [ rust-ratatui ]
    specfile_path: rust-ratatui.spec
    downstream_package_name: rust-ratatui
    upstream_package_name: ratatui
    actions: *actions-rust2rpm
  rust-rust-ini:
    # For rust-config
    # https://bugzilla.redhat.com/show_bug.cgi?id=2193253
    paths: [ rust-rust-ini ]
    specfile_path: rust-rust-ini.spec
    downstream_package_name: rust-rust-ini
    upstream_package_name: rust-ini
    actions: *actions-rust2rpm
  rust-saphyr:
    # For rust-config
    paths: [ rust-saphyr ]
    specfile_path: rust-saphyr.spec
    downstream_package_name: rust-saphyr
    upstream_package_name: saphyr
    actions: *actions-rust2rpm
  rust-saphyr-parser:
    # For saphyr
    paths: [ rust-saphyr-parser ]
    specfile_path: rust-saphyr-parser.spec
    downstream_package_name: rust-saphyr-parser
    upstream_package_name: saphyr-parser
    actions: *actions-rust2rpm
  rust-trim-in-place:
    # For rust-ini
    paths: [ rust-trim-in-place ]
    specfile_path: rust-trim-in-place.spec
    downstream_package_name: rust-trim-in-place
    upstream_package_name: trim-in-place
    actions: *actions-rust2rpm

srpm_build_deps:
  - rust2rpm

targets:
  - fedora-rawhide

jobs:
  - job: copr_build
    trigger: commit
    owner: lecris
    project: atuin
