_:
  - &actions-use-spec
    fix-spec-file: []
    create-archive:
      - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
    get-current-version:
      - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  - &actions-rust2rpm
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm @${PACKIT_PROJECT_VERSION}'
  - &actions-rust2rpm-with-patch
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm -r @${PACKIT_PROJECT_VERSION}'

packages:
  rust-config:
    # For atuin
    # https://bugzilla.redhat.com/show_bug.cgi?id=2262210
    paths: [ rust-config ]
    specfile_path: rust-config.spec
    downstream_package_name: rust-config
    upstream_package_name: config
    actions: *actions-rust2rpm-with-patch
  rust-dlv-list:
    # For ordered-multimap
    # https://bugzilla.redhat.com/show_bug.cgi?id=1989392
    paths: [ rust-dlv-list ]
    specfile_path: rust-dlv-list.spec
    downstream_package_name: rust-dlv-list
    upstream_package_name: dlv-list
    actions: *actions-rust2rpm-with-patch
  rust-hashlink:
    # For yaml-rust2
    # https://bugzilla.redhat.com/show_bug.cgi?id=2331134
    paths: [ rust-hashlink ]
    specfile_path: rust-hashlink.spec
    downstream_package_name: rust-hashlink
    upstream_package_name: hashlink
    actions: *actions-rust2rpm
  rust-ordered-multimap:
    # For rust-ini
    # https://bugzilla.redhat.com/show_bug.cgi?id=1976416
    paths: [ rust-ordered-multimap ]
    specfile_path: rust-ordered-multimap.spec
    downstream_package_name: rust-ordered-multimap
    upstream_package_name: ordered-multimap
    actions: *actions-rust2rpm-with-patch
  rust-rust-ini:
    # For rust-config
    # https://bugzilla.redhat.com/show_bug.cgi?id=2193253
    paths: [ rust-rust-ini ]
    specfile_path: rust-rust-ini.spec
    downstream_package_name: rust-rust-ini
    upstream_package_name: rust-ini
    actions: *actions-rust2rpm
  rust-yaml-rust2:
    # For rust-config
    paths: [ rust-yaml-rust2 ]
    specfile_path: rust-yaml-rust2.spec
    downstream_package_name: rust-yaml-rust2
    upstream_package_name: yaml-rust2
    actions: *actions-rust2rpm-with-patch
  fido-device-onboard:
    # Uses rust-config
    paths: [ fido-device-onboard ]
    specfile_path: fido-device-onboard.spec
    downstream_package_name: fido-device-onboard
    actions: *actions-use-spec
  keylime-agent-rust:
    # Uses rust-config
    paths: [ keylime-agent-rust ]
    specfile_path: keylime-agent-rust.spec
    downstream_package_name: keylime-agent-rust
    actions: *actions-use-spec
  rust-binfmt-dispatcher:
    # Uses rust-config
    paths: [ rust-binfmt-dispatcher ]
    specfile_path: rust-binfmt-dispatcher.spec
    downstream_package_name: rust-binfmt-dispatcher
    actions: *actions-use-spec
  rust-erdtree:
    # Uses rust-config
    paths: [ rust-erdtree ]
    specfile_path: rust-erdtree.spec
    downstream_package_name: rust-erdtree
    actions: *actions-use-spec
  rust-asahi-btsync:
    # Uses rust-rust-ini
    paths: [ rust-asahi-btsync ]
    specfile_path: rust-asahi-btsync.spec
    downstream_package_name: rust-asahi-btsync
    actions: *actions-use-spec
  rust-asahi-wifisync:
    # Uses rust-rust-ini
    paths: [ rust-asahi-wifisync ]
    specfile_path: rust-asahi-wifisync.spec
    downstream_package_name: rust-asahi-wifisync
    actions: *actions-use-spec
  rust-linicon-theme:
    # Uses rust-rust-ini
    paths: [ rust-linicon-theme ]
    specfile_path: rust-linicon-theme.spec
    downstream_package_name: rust-linicon-theme
    actions: *actions-use-spec
  rust-prefixdevname:
    # Uses rust-rust-ini
    paths: [ rust-prefixdevname ]
    specfile_path: rust-prefixdevname.spec
    downstream_package_name: rust-prefixdevname
    actions: *actions-use-spec
  rust-uu_env:
    # Uses rust-rust-ini
    paths: [ rust-uu_env ]
    specfile_path: rust-uu_env.spec
    downstream_package_name: rust-uu_env
    actions: *actions-use-spec
  rust-zram-generator:
    # Uses rust-rust-ini
    paths: [ rust-zram-generator ]
    specfile_path: rust-zram-generator.spec
    downstream_package_name: rust-zram-generator
    actions: *actions-use-spec
  tuigreet:
    # Uses rust-rust-ini
    paths: [ tuigreet ]
    specfile_path: tuigreet.spec
    downstream_package_name: tuigreet
    actions: *actions-use-spec

srpm_build_deps:
  - rust2rpm
  - rust2rpm-helper

targets:
  - fedora-rawhide

jobs:
  - job: copr_build
    trigger: commit
    branch: impact-check/rust-config
    owner: lecris
    project: rust-config
