_:
  - &trigger
    trigger: commit
    branch: main
  - &actions-use-spec
    fix-spec-file: []
    create-archive:
      - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
    get-current-version:
      - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  - &actions-rust2rpm
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm @${PACKIT_PROJECT_VERSION}'
  - &actions-rust2rpm-with-patch
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm -r @${PACKIT_PROJECT_VERSION}'

packages:
  atuin:
    paths: [ atuin ]
    specfile_path: atuin.spec
    downstream_package_name: atuin
    upstream_package_name: atuin
    actions: *actions-use-spec
  rust-axum-server:
    # For atuin
    paths: [ rust-axum-server ]
    specfile_path: rust-axum-server.spec
    downstream_package_name: rust-axum-server
    upstream_package_name: axum-server
    actions: *actions-rust2rpm-with-patch
  rust-interim:
    # For atuin
    paths: [ rust-interim ]
    specfile_path: rust-interim.spec
    downstream_package_name: rust-interim
    upstream_package_name: interim
    actions: *actions-rust2rpm-with-patch

srpm_build_deps:
  - rust2rpm
  - rust2rpm-helper

targets:
  - fedora-rawhide

jobs:
  - job: copr_build
    owner: lecris
    project: atuin
    <<: *trigger
  - job: tests
    <<: *trigger
