[features]
hide = [
    # missing dependency: pulldown-cmark-to-cmark ^10.0.1
    "cleanup-markdown",
]

[requires]
build = [
    "/usr/bin/protoc",
]
lib = [
    "/usr/bin/protoc",
]

[scripts]
check.pre = [
    "%if 0%{?epel} && 0%{?epel} < 10",
    "export PROTOC='/usr/bin/protoc --experimental_allow_proto3_optional'",
    "%endif",
]
