[features]
hide = [
    # missing dependency: pulldown-cmark-to-cmark ^10.0.1
    "cleanup-markdown",
]

[[package.extra-patches]]
number = 10
file = "prost-build-0.14.3-Pass_experimental_allow_proto3_optional.patch"
comments = [
    "Pass --experimental_allow_proto3_optional to fix epel9 incompatibility with protoc",
    "https://github.com/tokio-rs/prost/issues/1410",
]

[requires]
build = [
    # Needed for the google/protobuf/* files in the tests
    "protobuf-devel",
]
lib = [
    "/usr/bin/protoc",
]
