# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate prost-build

Name:           rust-prost-build
Version:        0.14.3
Release:        %autorelease
Summary:        Generate Prost annotated Rust types from Protocol Buffers files

License:        Apache-2.0
URL:            https://crates.io/crates/prost-build
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  protobuf-devel

%global _description %{expand:
Generate Prost annotated Rust types from Protocol Buffers files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       protobuf-devel

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+format-devel %{_description}

This package contains library source intended for building other packages which
use the "format" feature of the "%{crate}" crate.

%files       -n %{name}+format-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * test_generate_no_empty_outputs: requires a files not included in published
#   crates
# * test_generate_deprecated: test fails on epel9 due to version of protobuf
%{cargo_test -- -- --exact %{shrink:
    --skip tests::test_generate_no_empty_outputs
    --skip tests::test_generate_deprecated
}}
%endif

%changelog
%autochangelog
