# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate octocrab

Name:           rust-octocrab
Version:        0.44.0
Release:        %autorelease
Summary:        Modern, extensible GitHub API client

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/octocrab
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A modern, extensible GitHub API client.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENCE-APACHE
%license %{crate_instdir}/LICENCE-MIT
%license %{crate_instdir}/src/api/licenses.rs
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+default-client-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-client-devel %{_description}

This package contains library source intended for building other packages which
use the "default-client" feature of the "%{crate}" crate.

%files       -n %{name}+default-client-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+follow-redirect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+follow-redirect-devel %{_description}

This package contains library source intended for building other packages which
use the "follow-redirect" feature of the "%{crate}" crate.

%files       -n %{name}+follow-redirect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-core" feature of the "%{crate}" crate.

%files       -n %{name}+futures-core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-util-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-util-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-util" feature of the "%{crate}" crate.

%files       -n %{name}+futures-util-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-timeout-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-timeout-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-timeout" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-timeout-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-tls" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opentls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opentls-devel %{_description}

This package contains library source intended for building other packages which
use the "opentls" feature of the "%{crate}" crate.

%files       -n %{name}+opentls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+retry-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+retry-devel %{_description}

This package contains library source intended for building other packages which
use the "retry" feature of the "%{crate}" crate.

%files       -n %{name}+retry-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-aws-lc-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-aws-lc-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-aws-lc-rs" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-aws-lc-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-ring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-ring-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-ring" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-ring-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-webpki-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-webpki-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-webpki-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-webpki-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-devel %{_description}

This package contains library source intended for building other packages which
use the "stream" feature of the "%{crate}" crate.

%files       -n %{name}+stream-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+timeout-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+timeout-devel %{_description}

This package contains library source intended for building other packages which
use the "timeout" feature of the "%{crate}" crate.

%files       -n %{name}+timeout-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
