[package]
cargo-install-bin = false
license-files.include = [
    ".licenses/*"
]
cargo-toml-patch-comments = [
    """
    Drop libtest-mimic because it is too old
    (Used in tests/yaml-test-suite.rs)
    """,
]

[scripts]
install.post = [
    "install -Dp .licenses/* -t %{buildroot}%{crate_instdir}/.licenses",
]
