[package]
cargo-install-bin = false
license-files.include = [
    ".licenses/*"
]

[scripts]
install.pre = [
    "# Remove extraneous files from being installed",
    "rm -rf appveyor.yml garden.yml justfile",
]
install.post = [
    "install -Dp .licenses/* -t %{buildroot}%{crate_instdir}/.licenses",
]
