[features]
enable-all = true

[package]
cargo-toml-patch-comments = [
    "Relax libsqlite3 dependency",
    "Drop unpackaged libsqlite3 features",
]

[tests]
comments = [
    "resolve dependency loop with sqlx",
]
run = ["none"]

