[features]
hide = ["termwiz"]

[requires]
build = [
    "tomcli",
]

[scripts]
prep.post = [
    "# Drop unused dependency font8x8.",
    "# https://github.com/ratatui/ratatui/pull/1777",
    "tomcli set Cargo.toml del dev-dependencies.font8x8",
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
    "# Do not depend on fakeit; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.fakeit",
    "tomcli set Cargo.toml lists delitem --key=path example 'examples/table.rs'",
    "# Remove octocrab dependency and example",
    "tomcli set Cargo.toml del dev-dependencies.octocrab",
    "tomcli set Cargo.toml lists delitem --key=path example 'examples/async.rs'",
    "# remove executable bits from source files",
    "find -type f -executable -print -exec chmod -x {} +",
]

[tests]
skip = [
    "buffer::buffer::Buffer::pos_of",
    "buffer::buffer::tests::pos_of_panics_on_out_of_bounds",
]
comments = [
    "- buffer::buffer::Buffer::pos_of this one panics only if in debug.",
    "- buffer::buffer::tests::pos_of_panics_on_out_of_bounds same test as above",
]

