[package]
cargo-install-bin = false

[features]
hide = [
    "bin",
]

[scripts]
prep.post = [
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/file/mod.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/compile/mod.rs",
]
