[package]
cargo-install-bin = false
# Manually include the Provides(bundled) as well
cargo-toml-patch-comments = [
    """
    Fix the license metadata
    https://github.com/andrewhickman/protox/pull/92
    """,
]

[features]
hide = [
    "bin",
]


[scripts]
prep.post = [
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/file/mod.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/compile/mod.rs",
]
