# Generated by rust2rpm 27
%bcond check 1

%global crate protox

Name:           rust-protox
Version:        0.7.2
Release:        %autorelease
Summary:        Rust implementation of the protobuf compiler

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/protox
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A rust implementation of the protobuf compiler.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%license protobuf/LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/protox

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/protobuf/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bin-devel %{_description}

This package contains library source intended for building other packages which
use the "bin" feature of the "%{crate}" crate.

%files       -n %{name}+bin-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f bin

%build
%cargo_build -f bin
%{cargo_license_summary -f bin}
%{cargo_license -f bin} > LICENSE.dependencies

%install
%cargo_install -f bin

%if %{with check}
%check
%cargo_test -f bin
%endif

%changelog
%autochangelog
