[package]
cargo-install-bin = false

[features]
hide = [
    "bin",
]

[requires]
build = [
    "tomcli",
]

[scripts]
prep.post = [
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/file/mod.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/compile/mod.rs",
    "# Fix the license metadata",
    "# https://github.com/andrewhickman/protox/pull/92",
    "tomcli set Cargo.toml str package.license '(MIT OR Apache-2.0) AND BSD-3-Clause'",
]
