[package]
cargo-install-bin = false

[[package.extra-patches]]
number = 10
file = "protox-0.9.1-Pass_experimental_allow_proto3_optional.patch"
comments = [
    "Pass --experimental_allow_proto3_optional to fix epel9 incompatibility with protoc",
    "https://github.com/tokio-rs/prost/issues/1410",
]

[features]
hide = [
    "bin",
]

[requires]
build = [
    # Needed for the google/protobuf/* files in the tests
    "protobuf-devel",
]

[tests]
skip = [
    "google_map_proto2_unittest",
    "google_map_unittest",
    "google_protobuf_any",
    "google_protobuf_api",
    "google_protobuf_compiler_plugin",
    "google_protobuf_descriptor",
    "google_protobuf_duration",
    "google_protobuf_empty",
    "google_protobuf_field_mask",
    "google_protobuf_source_context",
    "google_protobuf_struct",
    "google_protobuf_timestamp",
    "google_protobuf_type",
    "google_protobuf_wrappers",
    "google_test_messages_proto2",
    "google_test_messages_proto3",
    "google_unittest",
    "google_unittest_empty",
    "google_unittest_enormous_descriptor",
    "google_unittest_import",
    "google_unittest_no_field_presence",
    "google_unittest_preserve_unknown_enum",
    "google_unittest_preserve_unknown_enum2",
    "google_unittest_proto3",
    "google_unittest_proto3_optional",
    "google_unittest_well_known_types",
    "reserved_ranges",
]
skip-exact = true
comments = [
    "google_*: Tries to access files in src/protobuf/* which are stripped",
    """\
    reserved_ranges: On epel9 the protoc and protox give different results, but not sure if it's different to Fedora also
    https://github.com/andrewhickman/protox/issues/101
    """,
]
