[requires]
build = [
    "tomcli",
]

[scripts]
prep.post = [
    "# Relax logos dependency",
    "tomcli set Cargo.toml str dependencies.logos '>=0.14.0,<0.16'",
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/lex/mod.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/lib.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/parse/mod.rs",
]