[package]
cargo-toml-patch-comments = [
    "Relax logos dependency",
]

[scripts]
prep.post = [
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/lex/mod.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/lib.rs",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/parse/mod.rs",
]