# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate protox-parse

Name:           rust-protox-parse
Version:        0.9.0
Release:        %autorelease
Summary:        Parsing of protobuf source files

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/protox-parse
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * Relax logos dependency
Patch:          protox-parse-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Parsing of protobuf source files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * We do not seem to produce the same output as upstream
%{cargo_test -- -- %{shrink:
    --skip parse::tests::parse_enum
    --skip parse::tests::parse_extension
    --skip parse::tests::parse_field
    --skip parse::tests::parse_file
    --skip parse::tests::parse_group
    --skip parse::tests::parse_import
    --skip parse::tests::parse_message
    --skip parse::tests::parse_oneof
    --skip parse::tests::parse_option
    --skip parse::tests::parse_package
    --skip parse::tests::parse_reserved
    --skip parse::tests::parse_service
    --skip parse::tests::parse_text_format_message
    --skip tests::enum_reserved_range_extrema
    --skip tests::enum_value_extrema
    --skip tests::field_default_invalid_type
    --skip tests::field_default_value
    --skip tests::imports
    --skip tests::invalid_message_number
    --skip tests::map_field_invalid_type
    --skip tests::message_field_json_name
    --skip tests::message_reserved_range_extrema
    --skip tests::negative_ident_outside_default
    --skip tests::options
    --skip tests::parse_field_default
    --skip tests::reserved_range
    --skip tests::syntax
}}
%endif

%changelog
%autochangelog
