[features]
hide = [
    "derive",
]

[package]
cargo-toml-patch-comments = [
    "Relax logos dependency",
]
exclude-crate-files = [
    # These files are for tests and docs only
    "src/file_descriptor_set.bin",
    "src/doctest.proto",
    "doc",
    "tests",
]
