[package]
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]

[[package.extra-sources]]
number = 2
file = "https://raw.githubusercontent.com/andrewhickman/prost-reflect/refs/tags/%{version}/LICENSE-APACHE"

[[package.extra-sources]]
number = 3
file = "https://raw.githubusercontent.com/andrewhickman/prost-reflect/refs/tags/%{version}/LICENSE-MIT"

[scripts]
prep.post = [
    "cp %{SOURCE2} .",
    "cp %{SOURCE3} .",
]
