[features]
hide = [
    "derive",
]

[requires]
build = [
    "tomcli",
]

[scripts]
prep.post = [
    "# Relax logos dependency",
    "tomcli set Cargo.toml str dependencies.logos.version '>=0.14.0,<0.16'",
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/descriptor/mod.rs",
]

[tests]
skip = [
    "dynamic::DynamicMessage::decode",
    "dynamic::DynamicMessage::fmt",
    "dynamic::DynamicMessage::has_field",
    "dynamic::DynamicMessage::try_set_field",
    "dynamic::DynamicMessage::try_set_field_by_name",
    "dynamic::DynamicMessage::try_set_field_by_number",
    "dynamic::unknown::UnknownField::decode",
    "dynamic::unknown::UnknownField::decode_value",
    "dynamic::unknown::UnknownField::fmt",
    "src/lib.rs",
    "dynamic::type_sizes",
]
comments = [
    "- Almost all tests are skipped because they require file_descriptor_set.bin which is not included.",
    "- dynamic::type_sizes This test uses std::mem::size_of which is inconsistent on i686",
]
