[package]
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]

[[package.extra-sources]]
number = 2
file = "https://raw.githubusercontent.com/andrewhickman/prost-reflect/refs/tags/0.14.6/LICENSE-APACHE"

[[package.extra-sources]]
number = 3
file = "https://raw.githubusercontent.com/andrewhickman/prost-reflect/refs/tags/0.14.6/LICENSE-MIT"

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "cp %{SOURCE2} .",
    "cp %{SOURCE3} .",
    "# Avoid circular dependency with protox",
    "# https://github.com/andrewhickman/prost-reflect/issues/154",
    "tomcli set Cargo.toml del dev-dependencies.protox",
    "# Disable test that use protox",
    "sed -r -i 's/(fn compare_parsed_and_coded_default_descriptors.*)/#[cfg(any())]\\n\\1/' src/reflect/wkt.rs",
    "sed -r -i 's/(fn expected_well_known_types.*)/#[cfg(any())]\\n\\1/' src/reflect/wkt.rs",
    "# Broken test because tests.rs is not in crate",
    "sed -i '/#\\[cfg(test)\\]/,/mod tests/d' src/descriptor/mod.rs",
]

[tests]
skip = [
    "dynamic::DynamicMessage::decode",
    "dynamic::DynamicMessage::fmt",
    "dynamic::DynamicMessage::has_field",
    "dynamic::DynamicMessage::try_set_field",
    "dynamic::DynamicMessage::try_set_field_by_name",
    "dynamic::DynamicMessage::try_set_field_by_number",
    "dynamic::unknown::UnknownField::decode",
    "dynamic::unknown::UnknownField::decode_value",
    "dynamic::unknown::UnknownField::fmt",
]
comments = [
    "These tests require file_descriptor_set.bin which is not included.",
]
