[features]
hide = [
    "derive",
]

[package]
cargo-toml-patch-comments = [
    "Relax logos dependency",
]
exclude-crate-files = [
    # This file is for tests only
    "src/file_descriptor_set.bin",
]
